### ISSUE TITLE
SMART data reported for wrong drives

### ISSUE THREAD

**Issue by GentleGiantSoftware** [DoogeJ/SmartHDD#1]
The code makes an incorrect assumption that MSStorageDriver_FailurePredictData returns the same drives as Win32_DiskDrive and Win32_PhysicalMedia which is not true. MSStorageDriver_FailurePredictData does not return information for USB memory sticks while they are included in the other lists. As a result the printed output might be incorrect.

**Comment by NoxiousPluK** [comment]
Ah!

Would this cause an issue in the offset of drive name and actual returned data?

I think I had issues like that lately, where two Intel SSD's of the same make/model seemed to return different data.

Thanks for contributing!

**Comment by NoxiousPluK** [comment]
Fixed by @ckaczor 👍
